"""Generate per-installation Windows launchers around the bundled adapter.

Setup only publishes private local files. Store/package discovery and native
launch probes run later through the packaged PowerShell implementation, so an
installed Desktop is not a prerequisite for setting up the callback CLI.
"""
from __future__ import annotations

import argparse
import importlib.metadata
import json
import os
from pathlib import Path
import subprocess
import sys

from .callback_transport import configuration_path
from .desktop_connection import load_bridge_endpoint
from .runtime import worker_command
from .storage import write_private_text, write_request


LAUNCHER_NAME = "Start LTC Desktop.cmd"
POWERSHELL_NAME = "Start LTC Desktop.ps1"
LAUNCH_MODES = ("direct", "package-context")


def powershell() -> Path:
    return Path(os.environ.get("SystemRoot", r"C:\Windows")) / "System32/WindowsPowerShell/v1.0/powershell.exe"


def launcher_resource() -> Path:
    path = Path(__file__).with_name("desktop_windows_assets") / "start-desktop-bridge.ps1"
    if not path.is_file():
        raise ValueError("Windows Desktop launcher resources are missing; reinstall the complete LTC package")
    return path


def installed_wrapper() -> Path:
    """Find this distribution's executable, including pip --user and pipx.

    Looking it up in RECORD avoids accidentally choosing another installation
    on PATH, or assuming scripts live beside the Python interpreter.
    """
    try:
        distribution = importlib.metadata.distribution("codex-long-task-callback")
    except importlib.metadata.PackageNotFoundError as error:
        raise ValueError("Install LTC before preparing Desktop, or supply --wrapper with its executable") from error
    candidates = {Path(distribution.locate_file(entry)).resolve()
                  for entry in distribution.files or ()
                  if entry.name.lower() == "ltc-desktop-core.exe"}
    candidates = {path for path in candidates if path.is_file()}
    if len(candidates) != 1:
        raise ValueError("Cannot locate this installation's ltc-desktop-core.exe; reinstall LTC or supply --wrapper")
    return candidates.pop()


def executable_path(value: str | Path) -> Path:
    path = Path(value).expanduser().absolute()
    if path.suffix.lower() != ".exe" or not path.is_file():
        raise ValueError(f"Expected an existing Windows executable: {path}")
    return path


def ps_literal(value: str) -> str:
    if any(character in value for character in ("\x00", "\r", "\n")):
        raise ValueError("Launcher paths must not contain NUL or newlines")
    return "'" + value.replace("'", "''") + "'"


def write_launchers(profile: Path) -> tuple[Path, Path]:
    state = configuration_path(profile).parent
    launcher, script = state / LAUNCHER_NAME, state / POWERSHELL_NAME
    # Keep cmd source ASCII; %~dp0 resolves Unicode paths at runtime without
    # relying on the console's codepage. PowerShell 5.1 requires a UTF-8 BOM.
    batch = (
        "@echo off\r\nsetlocal DisableDelayedExpansion\r\n"
        '"%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" '
        '-NoLogo -NoProfile -ExecutionPolicy Bypass -File "%~dp0Start LTC Desktop.ps1"\r\n'
        'set "ltc_exit=%errorlevel%"\r\n'
        'if not "%ltc_exit%"=="0" pause\r\nexit /b %ltc_exit%\r\n'
    )
    script_text = (
        "\ufeff# Generated by ltc setup for this installation.\n"
        "$ErrorActionPreference = 'Stop'\n$env:CODEX_HOME = " + ps_literal(str(profile)) + "\n& "
        + " ".join(ps_literal(argument) for argument in worker_command("desktop", "launch"))
        + "\nexit $LASTEXITCODE\n"
    )
    for path, content in ((script, script_text), (launcher, batch)):
        if path.is_symlink():
            raise ValueError(f"Refusing to replace a launcher symlink: {path}")
        write_private_text(path, content)
    return launcher, script


def read_config(profile: Path) -> dict[str, object]:
    config = json.loads(configuration_path(profile).read_text(encoding="utf-8"))
    if (not isinstance(config, dict) or config.get("version") != 1
            or config.get("platform") != "win32"
            or not isinstance(config.get("codex_home"), str)
            or os.path.normcase(config["codex_home"]) != os.path.normcase(str(profile.resolve()))):
        raise ValueError("Desktop configuration does not match this Windows profile")
    if config.get("launch_mode") not in LAUNCH_MODES:
        raise ValueError("Windows Desktop launch mode is invalid")
    for key in ("wrapper", "metadata", "desktop", "core"):
        value = config.get(key)
        if key in ("desktop", "core") and value is None:
            continue
        if not isinstance(value, str) or not Path(value).is_absolute():
            raise ValueError(f"Desktop configuration contains an invalid {key} path")
    if type(config.get("managed_wrapper")) is not bool:
        raise ValueError("Desktop configuration has no wrapper ownership setting")
    return config


def prepare_configuration(profile: Path, *, app: str | None = None, core: str | None = None,
                          wrapper: str | None = None, launch_mode: str | None = None,
                          force: bool = False, keep_existing: bool = False) -> dict[str, object]:
    profile = profile.resolve()
    config_path = configuration_path(profile)
    previous: dict[str, object] = {}
    if config_path.exists():
        if not (force or keep_existing):
            raise ValueError("Desktop configuration exists; use --force to replace it")
        try:
            previous = read_config(profile)
        except (OSError, ValueError):
            if not force:
                raise
    write_launchers(profile)
    launcher_resource()
    mode = launch_mode or previous.get("launch_mode", "direct")
    if mode not in LAUNCH_MODES:
        raise ValueError("Windows Desktop launch mode must be direct or package-context")
    managed = wrapper is None and previous.get("managed_wrapper", True)
    selected_wrapper = (installed_wrapper() if managed else
                        executable_path(wrapper or str(previous["wrapper"])))
    selected_app = app if app is not None else previous.get("desktop")
    selected_core = core if core is not None else previous.get("core")
    metadata = previous.get("metadata") or os.environ.get("CODEX_LONG_TASK_WAKEUP_DESKTOP_BRIDGE_FILE")
    metadata = Path(str(metadata)).expanduser() if metadata else profile / "long-task-wakeup/desktop-bridge.json"
    if not metadata.is_absolute():
        raise ValueError("Desktop bridge metadata must use an absolute path")
    config = {"version": 1, "platform": "win32", "codex_home": str(profile),
              "desktop": str(executable_path(selected_app)) if selected_app else None,
              "core": str(executable_path(selected_core)) if selected_core else None,
              "wrapper": str(selected_wrapper), "managed_wrapper": bool(managed),
              "metadata": str(metadata), "launch_mode": mode}
    write_request(config_path, config)
    return config


def install_for_setup(profile: Path, *, app: str | None = None, launch_mode: str | None = None) -> None:
    profile = profile.resolve()
    launcher = configuration_path(profile).parent / LAUNCHER_NAME
    try:
        config = prepare_configuration(profile, app=app, launch_mode=launch_mode, keep_existing=True)
    except (OSError, ValueError) as error:
        write_launchers(profile)
        print(f"Installed Desktop launcher to {launcher}")
        print(f"ltc: Desktop launcher needs configuration: {error}. CLI setup can continue.", file=sys.stderr)
    else:
        print(f"Installed Desktop launcher to {launcher} (launch mode: {config['launch_mode']}; "
              "Desktop discovery/preflight runs when launched)")


def launch_command(config: dict[str, object], *, check_only: bool) -> list[str]:
    host = powershell()
    if not host.is_file():
        raise ValueError("Windows PowerShell is unavailable")
    wrapper = executable_path(str(config["wrapper"]))
    command = [str(host), "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass",
               "-File", str(launcher_resource()), "-Python", sys.executable,
               "-CodexHome", str(config["codex_home"]), "-CoreWrapper", str(wrapper),
               "-BridgeFile", str(config["metadata"])]
    for key, option in (("desktop", "-DesktopExe"), ("core", "-CodexBin")):
        if config.get(key):
            command.extend([option, str(executable_path(str(config[key])))])
    if config["launch_mode"] == "package-context":
        command.append("-PackageContext")
    if check_only:
        command.append("-CheckOnly")
    return command


def command(args: argparse.Namespace) -> int:
    from .cli import codex_home

    try:
        if sys.platform != "win32":
            raise ValueError("Windows Desktop launchers require native Windows")
        profile = codex_home().resolve()
        if args.desktop_action == "prepare":
            config = prepare_configuration(profile, app=args.app, wrapper=args.wrapper,
                                           core=args.core, launch_mode=args.launch_mode, force=args.force)
            print(json.dumps({"prepared": True, "configuration": str(configuration_path(profile)),
                              "launcher": str(configuration_path(profile).parent / LAUNCHER_NAME),
                              "launch_mode": config["launch_mode"], "launch_preflight_performed": False,
                              "callback_verified": False}, ensure_ascii=False))
            return 0
        if args.desktop_action == "launch" and not args.check_only and not configuration_path(profile).exists():
            prepare_configuration(profile)
        config = read_config(profile)
        if args.desktop_action == "status":
            report = {"configured": True, "launch_mode": config["launch_mode"],
                      "bridge_running": False, "callback_verified": False}
            try:
                endpoint = load_bridge_endpoint(Path(str(config["metadata"])), profile)
            except (OSError, ValueError) as error:
                report["reason"] = str(error)
                print(json.dumps(report, ensure_ascii=False))
                return 1
            report.update(bridge_running=True, bridge_pid=endpoint.pid)
            print(json.dumps(report, ensure_ascii=False))
            return 0
        # Desktop will create its own fresh tool pipe and session bindings.
        environment = dict(os.environ)
        for name in ("CODEX_APP_TOOLS_PIPE_PATH", "CODEX_THREAD_ID", "CODEX_SESSION_ID",
                     "CODEX_APP_SERVER_USE_LOCAL_DAEMON"):
            environment.pop(name, None)
        return subprocess.call(launch_command(config, check_only=args.check_only), env=environment, shell=False)
    except (OSError, ValueError) as error:
        print(f"ltc: Desktop: {error}", file=sys.stderr)
        return 2
