"""Opt-in macOS Desktop launcher; never stops a running Desktop or edits it."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import plistlib
import shlex
import subprocess
import sys
import time

from .callback_transport import configuration_path
from .desktop_connection import load_unix_bridge_endpoint
from .desktop_core import BRIDGE_FILE_ENV, REAL_CODEX_ENV
from .runtime import worker_command
from .storage import write_private_text, write_request


LAUNCHER_NAME = "Start LTC Desktop.command"
WRAPPER_NAME = "desktop-core.command"


def bundle_executables(app: Path) -> tuple[Path, Path]:
    info = plistlib.loads((app / "Contents/Info.plist").read_bytes())
    if not isinstance(info, dict):
        raise ValueError("Desktop bundle Info.plist is invalid")
    name = info.get("CFBundleExecutable")
    if not isinstance(name, str) or not name or Path(name).name != name:
        raise ValueError("Desktop bundle executable is invalid")
    desktop = app / "Contents/MacOS" / name
    core = app / "Contents/Resources/codex"
    for path in (desktop, core):
        if not path.is_file() or not os.access(path, os.X_OK):
            raise ValueError(f"Required executable is unavailable: {path}")
    return desktop, core


def discover_app(explicit: str | Path | None = None) -> Path:
    if explicit is not None:
        try:
            app = Path(explicit).expanduser().resolve()
        except RuntimeError as error:
            raise ValueError("Desktop app path contains a symlink loop") from error
        bundle_executables(app)
        return app
    candidates = set()
    for directory in (Path("/Applications"), Path.home() / "Applications"):
        for name in ("Codex.app", "ChatGPT.app"):
            try:
                app = (directory / name).resolve()
                bundle_executables(app)
            except (OSError, ValueError, RuntimeError, plistlib.InvalidFileException):
                continue
            candidates.add(app)
    if not candidates:
        raise ValueError("No Codex Desktop bundle found. Install Desktop, or select its location with "
                         "ltc desktop prepare --app /path/to/Codex.app")
    if len(candidates) != 1:
        raise ValueError("Multiple Codex Desktop bundles found; select one with ltc desktop prepare --app: "
                         + ", ".join(str(app) for app in sorted(candidates)))
    return candidates.pop()


def paths(app: Path, wrapper: Path, profile: Path) -> dict[str, object]:
    if not app.is_absolute() or not wrapper.is_absolute():
        raise ValueError("Desktop app and Core wrapper paths must be absolute")
    desktop, core = bundle_executables(app)
    if not wrapper.is_file() or not os.access(wrapper, os.X_OK):
        raise ValueError(f"Required executable is unavailable: {wrapper}")
    metadata = profile / "long-task-wakeup/desktop/bridge.json"
    if len(os.fsencode(metadata.parent / "core.sock")) > 103:
        raise ValueError("Profile path is too long for the macOS Desktop socket")
    return {"version": 1, "codex_home": str(profile.resolve()), "desktop": str(desktop),
            "core": str(core), "wrapper": str(wrapper), "metadata": str(metadata)}


def write_launchers(profile: Path) -> tuple[Path, Path]:
    """Generate local artifacts from this installation, without PATH lookups.

    The Core shim works for venv, pipx and pip --user installations alike: the
    installed console-script directory need not be beside sys.executable.
    """
    state = configuration_path(profile).parent
    state.mkdir(mode=0o700, parents=True, exist_ok=True)
    launcher, wrapper = state / LAUNCHER_NAME, state / WRAPPER_NAME
    entry = str(Path(__file__).with_name("_desktop_entry.py").absolute())
    core_command = [sys.executable, entry]
    scripts = {
        launcher: ("#!/bin/sh\n# Generated by ltc setup for this installation.\n"
                   + "export CODEX_HOME=" + shlex.quote(str(profile)) + "\nexec "
                   + shlex.join(worker_command("desktop", "launch")) + "\n"),
        wrapper: ("#!/bin/sh\n# Generated by ltc setup for this installation.\nexec "
                  + shlex.join(core_command) + ' "$@"\n'),
    }
    for path, content in scripts.items():
        if path.is_symlink():
            raise ValueError(f"Refusing to replace a launcher symlink: {path}")
        write_private_text(path, content)
        path.chmod(0o700)
    return launcher, wrapper


def prepare_configuration(profile: Path, *, app: str | None = None, wrapper: str | None = None,
                          force: bool = False, keep_existing: bool = False) -> dict[str, object]:
    """Prepare without starting/probing Core or touching a running Desktop."""
    config_path = configuration_path(profile)
    previous = None
    if config_path.exists():
        if not (force or keep_existing):
            raise ValueError("Desktop configuration exists; use --force to replace it")
        try:
            previous = read_config(profile)
        except (OSError, ValueError):
            if not force:
                raise
    _, generated_wrapper = write_launchers(profile)
    # Repeated setup refreshes generated runtime paths but keeps app selection
    # and explicitly configured wrappers. Never choose a second app silently.
    if previous is not None:
        if app is None:
            app = str(Path(str(previous["desktop"])).parent.parent.parent)
        if wrapper is None:
            wrapper = str(previous["wrapper"])
    selected_app = discover_app(app)
    selected_wrapper = Path(wrapper).expanduser().absolute() if wrapper else generated_wrapper
    config = paths(selected_app, selected_wrapper, profile)
    if previous is not None:
        config["metadata"] = previous["metadata"]
    write_request(config_path, config)
    return config


def install_for_setup(profile: Path, *, app: str | None = None) -> None:
    """Desktop is optional: leave a usable launcher even before app installation."""
    profile = profile.resolve()
    launcher = configuration_path(profile).parent / LAUNCHER_NAME
    try:
        prepare_configuration(profile, app=app, keep_existing=True)
    except (OSError, ValueError, plistlib.InvalidFileException) as error:
        # Even a pre-existing invalid configuration must not prevent generating
        # the entry points. The saved settings are left for explicit repair.
        write_launchers(profile)
        print(f"Installed Desktop launcher to {launcher}")
        print(f"ltc: Desktop launcher needs configuration: {error}. CLI setup can continue.", file=sys.stderr)
    else:
        print(f"Installed Desktop launcher to {launcher} (shared Core activates when you launch it)")


def launch_environment(config: dict[str, object]) -> dict[str, str]:
    environment = dict(os.environ)
    environment.update({"CODEX_HOME": str(config["codex_home"]), "CODEX_CLI_PATH": str(config["wrapper"]),
                        "CODEX_APP_SERVER_FORCE_CLI": "1", REAL_CODEX_ENV: str(config["core"]),
                        BRIDGE_FILE_ENV: str(config["metadata"]), "CODEX_LONG_TASK_WAKEUP_DESKTOP_APP_SERVER": "1"})
    environment.pop("CODEX_APP_SERVER_WS_URL", None)
    environment.pop("CODEX_APP_SERVER_USE_LOCAL_DAEMON", None)
    # The new Desktop creates fresh per-process tool pipes and session bindings.
    for name in ("CODEX_APP_TOOLS_PIPE_PATH", "CODEX_THREAD_ID", "CODEX_SESSION_ID"):
        environment.pop(name, None)
    return environment


def running_desktop(executable: Path) -> list[int]:
    result = subprocess.run(["/bin/ps", "-axo", "pid=,comm="], capture_output=True, text=True, timeout=5)
    if result.returncode:
        raise ValueError("Could not inspect Desktop processes; recheck from an ordinary terminal")
    found = []
    for line in result.stdout.splitlines():
        fields = line.strip().split(None, 1)
        if len(fields) == 2 and fields[1] == str(executable):
            found.append(int(fields[0]))
    return found


def read_config(profile: Path) -> dict[str, object]:
    config = json.loads(configuration_path(profile).read_text(encoding="utf-8"))
    if (not isinstance(config, dict) or config.get("version") != 1
            or config.get("codex_home") != str(profile.resolve())):
        raise ValueError("Desktop configuration does not match this profile")
    for key in ("desktop", "core", "wrapper", "metadata"):
        if not isinstance(config.get(key), str) or not Path(config[key]).is_absolute():
            raise ValueError("Desktop configuration contains an invalid path")
    return config


def preflight(config: dict[str, object]) -> dict[str, object]:
    for key in ("desktop", "core", "wrapper"):
        path = Path(str(config[key]))
        if not path.is_file() or not os.access(path, os.X_OK):
            raise ValueError(f"Required {key} executable is unavailable")
    probe = subprocess.run([str(config["wrapper"]), "--version"], env=launch_environment(config),
                           capture_output=True, text=True, timeout=10)
    if probe.returncode != 0:
        raise ValueError("Core wrapper preflight failed; install this LTC build before preparing Desktop")
    blockers = []
    pids = running_desktop(Path(str(config["desktop"])))
    if pids:
        blockers.append("desktop_running")
    metadata = Path(str(config["metadata"]))
    if any(p.exists() or p.is_symlink() for p in (metadata, metadata.parent / "core.sock")):
        blockers.append("existing_bridge_state_requires_inspection")
    return {"configuration_valid": True, "launch_ready": not blockers, "launch_blockers": blockers,
            "desktop_pids": pids, "core_version": probe.stdout.strip(), "callback_verified": False}


def command(args: argparse.Namespace) -> int:
    from .cli import codex_home

    try:
        if sys.platform != "darwin":
            raise ValueError("This adapter requires macOS; use ltc desktop for automatic platform selection")
        profile = codex_home().resolve()
        config_path = configuration_path(profile)
        if args.desktop_action == "prepare":
            config = prepare_configuration(profile, app=args.app, wrapper=args.wrapper, force=args.force)
            report = preflight(config)
            launcher = config_path.parent / LAUNCHER_NAME
            print(json.dumps({**report, "prepared": True, "configuration": str(config_path), "launcher": str(launcher)}, ensure_ascii=False))
            return 0
        if args.desktop_action == "launch" and not args.check_only and not config_path.exists():
            # Setup may precede Desktop installation. First launch discovers
            # the app; status/check-only remain read-only.
            prepare_configuration(profile)
        config = read_config(profile)
        if args.desktop_action == "status":
            try:
                endpoint = load_unix_bridge_endpoint(Path(str(config["metadata"])), profile)
                print(json.dumps({"configured": True, "bridge_running": True, "core_pid": endpoint.pid,
                                  "callback_verified": False}))
                return 0
            except (OSError, ValueError):
                print(json.dumps({"configured": True, "bridge_running": False, "callback_verified": False}))
                return 1
        report = preflight(config)
        if args.check_only:
            print(json.dumps(report))
            return 0 if report["launch_ready"] else 1
        if not report["launch_ready"]:
            print(json.dumps(report))
            raise ValueError("Save active work and quit Desktop before launching; LTC does not stop it")
        log_path = config_path.parent / "desktop-launch.log"
        descriptor = os.open(log_path, os.O_WRONLY | os.O_APPEND | os.O_CREAT | os.O_NOFOLLOW, 0o600)
        with os.fdopen(descriptor, "ab", buffering=0) as log:
            process = subprocess.Popen([str(config["desktop"])], env=launch_environment(config),
                                       stdin=subprocess.DEVNULL, stdout=log, stderr=log, start_new_session=True)
        deadline = time.monotonic() + 20
        while time.monotonic() < deadline:
            try:
                endpoint = load_unix_bridge_endpoint(Path(str(config["metadata"])), profile)
                print(json.dumps({"desktop_started": True, "desktop_pid": process.pid, "core_pid": endpoint.pid,
                                  "callback_verified": False, "next_step": "Open the original session, check App Tools, and verify a real callback/ACK."}))
                return 0
            except (OSError, ValueError):
                if process.poll() is not None:
                    break
                time.sleep(0.1)
        raise ValueError(f"Desktop bridge did not become ready; inspect {log_path}")
    except (OSError, ValueError, plistlib.InvalidFileException, subprocess.TimeoutExpired) as error:
        print(f"ltc: Desktop: {error}", file=sys.stderr)
        return 2
