"""Opt-in real Linux service-lifetime test; never contacts an AI provider.

Run with LTC_TEST_SYSTEMD=1 after reviewing local service permissions. The test
creates only disposable, namespaced user services and a private temporary queue.
It does not stop/restart the installed LTC daemon or change user services.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
import textwrap
import time
import unittest
from pathlib import Path

from long_task_callback import cli
from long_task_callback.platforms import OwnerState, SystemdUserBackend


@unittest.skipUnless(os.environ.get("LTC_TEST_SYSTEMD") == "1", "set LTC_TEST_SYSTEMD=1 for real user-service test")
class RealSystemdIsolationTests(unittest.TestCase):
    def wait_until(self, predicate, explanation: str, timeout: float = 15.0) -> None:
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if predicate():
                return
            time.sleep(0.05)
        self.fail(explanation)

    def stop_units(self, *units: str) -> None:
        # Names are generated by the backend, never global daemon service names.
        subprocess.run(
            ["systemctl", "--user", "stop", *units], stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=10, check=False,
        )

    def control_group(self, owner: str) -> str:
        result = subprocess.run(
            ["systemctl", "--user", "show", "--property=ControlGroup", "--value", owner],
            stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            text=True, timeout=10, check=True,
        )
        return result.stdout.strip()

    def test_stopping_coordinator_service_preserves_workload_and_single_result_callback(self) -> None:
        backend = SystemdUserBackend()
        if not backend.available():
            self.skipTest("Linux systemd >=240 user manager is unavailable")
        with tempfile.TemporaryDirectory(prefix="ltc-real-systemd-") as temporary:
            directory = Path(temporary)
            root = directory / "queue"
            started = directory / "workload-started"
            release = directory / "allow-finish"
            executions = directory / "executions.txt"
            output = directory / "artifact.txt"
            workload = directory / "workload.py"
            workload.write_text(textwrap.dedent("""\
                import os
                import sys
                import time
                from pathlib import Path
                started, release, executions, output = map(Path, sys.argv[1:])
                with executions.open("a") as stream:
                    stream.write("executed\\n")
                started.write_text(str(os.getpid()))
                deadline = time.monotonic() + 45
                while not release.exists():
                    if time.monotonic() >= deadline:
                        raise SystemExit(99)
                    time.sleep(0.05)
                output.write_text("finished after coordinator stopped")
                raise SystemExit(7)
                """), encoding="utf-8")
            args = argparse.Namespace(
                backend="systemd", agent="codex", cwd=str(directory), task="real systemd isolation fixture",
                command=None, exit_code=None, message=None, session="fixture-no-real-agent-session",
                last=False, via_daemon=False, queue_dir=str(root), approvals_reviewer="auto_review",
                approval_policy="on-request", sandbox_mode="workspace-write", dry_run=False,
                strict=False, wrapped_command=[sys.executable, str(workload), str(started), str(release),
                                               str(executions), str(output)],
            )
            self.assertEqual(cli.run(args), 0)
            task_path = next(cli.managed_tasks_root(root).glob("*/task.json"))
            task = cli.load_managed_task(task_path)
            task_owner = backend.owner_name(str(task["id"]), 1, root)
            coordinator_owner = backend.owner_name("test-coordinator", 1, root)
            ready = directory / "coordinator-ready"
            coordinator = directory / "coordinator.py"
            source = str(Path(cli.__file__).resolve().parents[1])
            coordinator.write_text(textwrap.dedent(f"""\
                import sys
                import time
                from pathlib import Path
                sys.path.insert(0, {source!r})
                from long_task_callback import cli
                cli.recover_managed_tasks(Path(sys.argv[1]))
                Path(sys.argv[2]).write_text("launched")
                time.sleep(60)
                """), encoding="utf-8")
            try:
                backend.launch(
                    coordinator_owner, [sys.executable, str(coordinator), str(root), str(ready)],
                    directory, directory / "coordinator.log",
                )
                self.wait_until(lambda: ready.exists() and started.exists(), "worker did not start")
                coordinator_group = self.control_group(coordinator_owner)
                task_group = self.control_group(task_owner)
                self.assertTrue(coordinator_group)
                self.assertTrue(task_group)
                self.assertNotEqual(task_group, coordinator_group)
                self.assertFalse(task_group.startswith(coordinator_group + "/"))

                self.stop_units(coordinator_owner)
                self.assertEqual(backend.probe(task_owner), OwnerState.ALIVE)
                self.assertFalse(output.exists())
                cli.recover_managed_tasks(root)
                self.assertEqual(executions.read_text().splitlines(), ["executed"])

                release.write_text("finish", encoding="utf-8")
                callback_path = cli.request_path(root, "pending", str(task["id"]))
                self.wait_until(lambda: callback_path.exists(), "workload did not produce a durable callback")
                result = json.loads(cli.managed_result_path(root, str(task["id"])).read_text())
                self.assertEqual(result["exit_code"], 7)
                self.assertEqual(output.read_text(), "finished after coordinator stopped")
                self.assertEqual(cli.load_managed_task(task_path)["state"], "completed")
                cli.recover_managed_tasks(root)
                self.assertEqual(executions.read_text().splitlines(), ["executed"])
                self.assertEqual(len(list((root / "pending").glob("*.json"))), 1)
                callback = cli.load_request(callback_path)
                self.assertEqual(callback["target"], {"kind": "session", "value": "fixture-no-real-agent-session"})
                self.assertEqual(callback["exit_code"], 7)
                self.assertTrue(Path(callback["prompt_details_path"]).is_file())
            finally:
                self.stop_units(task_owner, coordinator_owner)


if __name__ == "__main__":
    unittest.main()
